export const  SAVE_NEW_ADDRESS_REQUEST = 'SAVE_NEW_ADDRESS_REQUEST';
export const  SAVE_NEW_ADDRESS_SUCCESS = 'SAVE_NEW_ADDRESS_SUCCESS';
export const  SAVE_NEW_ADDRESS_FAILURE= 'SAVE_NEW_ADDRESS_FAILURE';

export const  SET_DELIVERY_ADDRESS_REQUEST = 'SET_DELIVERY_ADDRESS_REQUEST';
export const  SET_DELIVERY_ADDRESS_SUCCESS = 'SET_DELIVERY_ADDRESS_SUCCESS';
export const  SET_DELIVERY_ADDRESS_FAILURE= 'SET_DELIVERY_ADDRESS_FAILURE';

export const  SET_CHECKOUT_REQUEST = 'SET_CHECKOUT_REQUEST';
export const  SET_CHECKOUT_SUCCESS = 'SET_CHECKOUT_SUCCESS';
export const  SET_CHECKOUT_FAILURE= 'SET_CHECKOUT_FAILURE';