export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST';
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE';
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS';

export const FIND_PRODUCTS_REQUEST = 'FIND_PRODUCTS_REQUEST';
export const FIND_PRODUCTS_FAILURE = 'FIND_PRODUCTS_FAILURE';
export const FIND_PRODUCTS_SUCCESS = 'FIND_PRODUCTS_SUCCESS';

export const GET_DATA_FOR_HOME_REQUEST = "GET_DATA_FOR_HOME_REQUEST";
export const GET_DATA_FOR_HOME_FAILURE = "GET_DATA_FOR_HOME_FAILURE";
export const GET_DATA_FOR_HOME_SUCCESS = "GET_DATA_FOR_HOME_SUCCESS";

export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST";
export const ADD_NEW_PRODUCT_FAILURE = "ADD_NEW_PRODUCT_FAILURE";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";